# Generated by Django 6.0.7 on 2026-08-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('contact', models.CharField(max_length=100, verbose_name='Telegram или телефон')),
                ('service', models.CharField(choices=[('basic', 'Базовый бот'), ('bot_db', 'Бот + база данных'), ('ai_agent', 'AI-агент')], default='basic', max_length=20, verbose_name='Услуга')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
