# Generated by Django 6.0.7 on 2026-08-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Сообщение'),
        ),
    ]
